### ISSUE TITLE
Generate all Mals localizations using a preferred language

### ISSUE THREAD

**Issue by mrthethatone** [ArchLeaders/MalsMerger#1]
Suggestion: Make it so that there is an option to track all changes made in the selected mals files regardless of language, and then on merge, generate a file of a preffered language containing the modified or added entries from the selected mals. Or another way to do it could be to generate every language with the entry of the preffered langauge.

**Comment by ArchLeaders** [comment]
For changelog generation, track all the mod changes regardless of this. When merging, however, generate every `Mals` localization, using the preferred language if the language is not tracked as a change.

### Examples

- If a mod *only* edits `USen`, generate every `Mals` archive with the changes from `USen`.
- If a mod edits `USen` and `EUfr`, and the preferred language is `USfr`, generate every `Mals` archive with the changes from `EUfr`.

### Process

- First, use the preferred localization if it exists.
- Otherwise, match the language of the preferred localization (over the region)
- If there is still no match, use the first archive.
